
networks:
  appsare:
    name: appsare
services:
  ar_postgres:
    image: postgres:14.12
    container_name: ar_postgres
    networks:
      - appsare
    ports:
      - 5434:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=appsare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  ar_php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ar_php
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
    networks:
      - appsare
  ar_nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ar_nginx
    depends_on:
      - ar_php
      - ar_postgres
    networks:
      - appsare
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped

  ar_composer:
    image: composer:latest
    container_name: ar_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - appsare

  ar_artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ar_artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - appsare
  ar_npm:
    image: node:current-alpine
    container_name: ar_npm
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - appsare
  ar_runtests:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ar_runtests
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "test"]
    networks:
      - appsare

  ar_scheduler:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ar_scheduler
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "schedule:work"]
    networks:
      - appsare
  ar_supervisord:
    build:
      context: .
      dockerfile: supervisord.dockerfile
    container_name: ar_supervisord
    depends_on:
      - ar_nginx
      - ar_php
      - ar_postgres
      - ar_scheduler
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - appsare
  ar_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ar_pgadmin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=madhukar@seasonsurvey.com'
      - 'PGADMIN_DEFAULT_PASSWORD=slash123'
    ports:
      - 8084:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - appsare
    
  
